name: Deploy Backend to Render

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys \
               -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               -d '{}'
